common:
    lid_topic:  "/ouster/points"
    imu_topic:  "/ouster/imu"

preprocess:
    #1 for Livox serials LiDAR (not compiled), 2 velodyne, 3 for L515 LiDAR (default), 4 My OUSTER
    lidar_type: 4
    scan_line: 32
    blind: 1
    point_filter_num: 1             #~ how many scan deal once
    calib_laser: false              # true for KITTI Odometry dataset

mapping:
    down_sample_size: 0.1           #~ downsize the (undistorted) input scan, not the map.
    max_iteration: 3                #~ iEKF max iteration 
    voxel_size: 0.25                #~ voxel size used for Hash and plane search
    max_layer: 4                    #~ octree max depth.
    layer_point_size: [20, 10, 10, 5, 5]        #~ how many points are used to "update" the voxel in each layer.
    plannar_threshold: 0.01         #~ check plane, minimal eigen value
    max_points_size: 200            #~ points in one voxel esceed this value, the voxel is no-update (n,q)+covariance
    max_cov_points_size: 200        #~ points in one voxel esceed this value, the voxel's covariance is no-update

noise_model:                        #~ Lidar measure uncertainty modeling
    ranging_cov: 0.02
    angle_cov: 0.25
    acc_cov_scale: 0.1
    gyr_cov_scale: 0.1

imu:
    imu_en: true                   #~ IMU is used for undistortion. fasle: use constant-velocity model; true: use imu propagation
    extrinsic_T: [ 0, 0, 0]
    extrinsic_R: [ 1, 0, 0, 
                   0, 1, 0, 
                   0, 0, 1]

visualization:
    pub_voxel_map: true
    publish_max_voxel_layer: 1        # only publish 0,1,2 layer's plane
    pub_point_cloud: true
    dense_map_enable: false           #~ publish the downsampled or full (undistorted) scan
    pub_point_cloud_skip: 5           # publish one points per five points

Result:
    write_kitti_log: false
    result_path: "/home/larry/Desktop/VoxelMap_result.txt"
